### ISSUE TITLE
QC data

### ISSUE THREAD

**Issue by tdido** [tdido/board_alegosto01#7]
This will be the first step of the pipeline.

Implement the following software into a Snakemake pipeline to QC nanopore data

- [x] https://github.com/wdecoster/NanoPlot
- [ ] https://github.com/GenomiqueENS/toulligQC
- [ ] https://github.com/a-slide/pycoQC

We will then look at the output and decide whether to keep one or more of them.

Data is located at `/storage/scratch01/groups/bu/myeloma_altum`

**Comment by alegosto01** [comment]
i have some doubts about ToulligQC, i understood that toulligqc needs Guppy basecaller output files : sequencing_summary.txt and sequencing_telemetry.js. I didn't know where to find them so i tried anyway to run this command, after creating the two files as empty files:
sbatch -o log.txt -e error.txt -J index_genome -c 10 --mem=32G -t720 --wrap "toulligqc -a ToulligQC/sequencing_summary.txt -t ToulligQC/sequencing_telemetry.js -f /storage/scratch01/groups/bu/myeloma_altum/altum/Sequencing_runs/1901449_nanopore.fastq.gz --output-directory ToulligQC"

and i got this error:


ERROR: Error while checking Fast5 configuration: The fast5 extension is not supported (fast5, tar.bz2 or tar.gz format): /storage/scratch01/groups/bu/myeloma_altum/altum/Sequencing_runs/1901449_nanopore.fastq.gz

i think i need a FAST5 file instead of FASTQ.

i tried also with the option -q instead of -f in before the fastq file path because in a website was written that it was the option to use FASTQ files but i got this error:

ToulligQC V2.2.3: error: unrecognized arguments: -q /storage/scratch01/groups/bu/myeloma_altum/altum/Sequencing_runs/1901449_nanopore.fastq.gz

**Comment by alegosto01** [comment]
Update:
I found this file:
/storage/scratch01/groups/bu/myeloma_altum/altum/Sequencing_runs/1901449_nanopore_20220517/no_sample/20220517_1140_MN38629_FAR64540_5c4e90ff/sequencing_summary_FAR64540_18bf4d69.txt
that i used as sequencing_summary.txt and this:
/storage/scratch01/groups/bu/myeloma_altum/altum/Sequencing_runs/1901449_nanopore_20220517/no_sample/20220517_1140_MN38629_FAR64540_5c4e90ff/report_FAR64540_20220517_1146_5c4e90ff.json
as sequencing_telemetry.js.
i didn't understand if i used the right files. I don't know if i can use a json file as a js file for the input.

i also found some fast5 files here:
/storage/scratch01/groups/bu/myeloma_altum/altum/Sequencing_runs/1901449_nanopore_20220517/no_sample/20220517_1140_MN38629_FAR64540_5c4e90ff/fast5/

i chose one of them and i run this huge command:

sbatch -o log.txt -e error.txt -J index_genome -c 10 --mem=32G -t720 \ 
--wrap "toulligqc -t /storage/scratch01/groups/bu/myeloma_altum/altum/Sequencing_runs/1901449_nanopore_20220517/no_sample/20220517_1140_MN38629_FAR64540_5c4e90ff/report_FAR64540_20220517_1146_5c4e90ff.json \
-a /storage/scratch01/groups/bu/myeloma_altum/altum/Sequencing_runs/1901449_nanopore_20220517/no_sample/20220517_1140_MN38629_FAR64540_5c4e90ff/sequencing_summary_FAR64540_18bf4d69.txt \ 
-f /storage/scratch01/groups/bu/myeloma_altum/altum/Sequencing_runs/1901449_nanopore_20220517/no_sample/20220517_1140_MN38629_FAR64540_5c4e90ff/fast5/FAR64540_18bf4d69_100.fast5 \
--output-directory ToulligQC"

and i got this error:

Traceback (most recent call last):
  File "/home/agostoli/mambaforge/envs/ToulligQC/bin/toulligqc", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/agostoli/mambaforge/envs/ToulligQC/lib/python3.11/site-packages/toulligqc/toulligqc.py", line 348, in main
    extractor.extract(result_dict)
  File "/home/agostoli/mambaforge/envs/ToulligQC/lib/python3.11/site-packages/toulligqc/sequencing_telemetry_extractor.py", line 103, in extract
    self._set_result_dict_value(result_dict, '.flowcell.id', array, 'tracking_id', 'flow_cell_id')
  File "/home/agostoli/mambaforge/envs/ToulligQC/lib/python3.11/site-packages/toulligqc/sequencing_telemetry_extractor.py", line 148, in _set_result_dict_value
    if dict_name in array[0] and dict_key in array[0][dict_name]:
                    ~~~~~^^^
KeyError: 0

**Comment by alegosto01** [comment]
i got an error using PycoQC as well, this is the command:
sbatch -o log.txt -e error.txt -J index_genome -c 10 --mem=32G -t720 \ 
--wrap "pycoQC –f /storage/scratch01/groups/bu/myeloma_altum/altum/Sequencing_runs/1901449_nanopore_20220517/no_sample/20220517_1140_MN38629_FAR64540_5c4e90ff/sequencing_summary_FAR64540_18bf4d69.txt \
–o PycoQC/run_1.html"

error:usage: pycoQC [-h] [--version]
              [--summary_file [SUMMARY_FILE [SUMMARY_FILE ...]]]
              [--barcode_file [BARCODE_FILE [BARCODE_FILE ...]]]
              [--bam_file [BAM_FILE [BAM_FILE ...]]]
              [--html_outfile HTML_OUTFILE] [--json_outfile JSON_OUTFILE]
              [--min_pass_qual MIN_PASS_QUAL] [--min_pass_len MIN_PASS_LEN]
              [--filter_calibration] [--filter_duplicated]
              [--min_barcode_percent MIN_BARCODE_PERCENT]
              [--report_title REPORT_TITLE] [--template_file TEMPLATE_FILE]
              [--config_file CONFIG_FILE] [--skip_coverage_plot]
              [--sample SAMPLE] [--default_config] [-v | -q]
pycoQC: error: unrecognized arguments: –f /storage/scratch01/groups/bu/myeloma_altum/altum/Sequencing_runs/1901449_nanopore_20220517/no_sample/20220517_1140_MN38629_FAR64540_5c4e90ff/sequencing_summary_FAR64540_18bf4d69.txt

**Comment by tdido** [comment]
For Toullig, it seems like you don't need the FAST5 file if you have summary and telemetry. Have you tried without it?

In the case of Pyco it just seems like it doesn't like `-f`. Have you tried `--summary_file` instead?
